// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nibm.Pdsa.Group4.Models;

namespace Nibm.Pdsa.Group4.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200409162804_addDistance")]
    partial class addDistance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Nibm.Pdsa.Group4.Models.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DistanceKm");

                    b.Property<int>("fromStationId");

                    b.Property<int>("toStationId");

                    b.HasKey("Id");

                    b.HasIndex("fromStationId");

                    b.HasIndex("toStationId");

                    b.ToTable("Distance");
                });

            modelBuilder.Entity("Nibm.Pdsa.Group4.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("Nibm.Pdsa.Group4.Models.Distance", b =>
                {
                    b.HasOne("Nibm.Pdsa.Group4.Models.Station", "fromStation")
                        .WithMany()
                        .HasForeignKey("fromStationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nibm.Pdsa.Group4.Models.Station", "toStation")
                        .WithMany()
                        .HasForeignKey("toStationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
